# Generated by Django 5.2.1 on 2025-06-05 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dupla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('participante_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplas_como_1', to='campeonato_bt.participante')),
                ('participante_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplas_como_2', to='campeonato_bt.participante')),
            ],
        ),
    ]
